
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI uses this URL for db push/migrations.
    // Default matches app runtime fallback in src/lib/db.ts.
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
